version: '3.6'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000" 
      - "9229:9229"
    command: npm run debug
    volumes:
      - ./src:/app/src