apiVersion: skaffold/v2beta7
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: backend
    context: .
    docker:
      dockerfile: Dockerfile.skaffold
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .