apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  ports:
  - port: 3000
  type: LoadBalancer
  selector:
    app: node
---

apiVersion: v1
kind: Service
metadata:
  name: node-debug-svc
spec:
  ports:
  - port: 9229
  type: LoadBalancer
  selector:
    app: node


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: backend:latest